g++ -I src/include -L src/lib -o main main.cpp -lmingw32 -lSDL2main -lSDL2
g++ -I src/include -L src/lib -o main base.cpp -lmingw32 -lSDL2main -lSDL2
g++ -I src/include -L src/lib -o main tutorial.cpp -lmingw32 -lSDL2main -lSDL2
g++ -I src/include -L src/lib -o main git.cpp -lmingw32 -lSDL2main -lSDL2