g++ -I src/include -L src/lib -o main Task_101.cpp -lmingw32 -lSDL2main -lSDL2
g++ -I src/include -L src/lib -o main Task_102.cpp -lmingw32 -lSDL2main -lSDL2
g++ -I src/include -L src/lib -o main Task_103.cpp -lmingw32 -lSDL2main -lSDL2